version: '3.8'

services:

  db:
    image: mysql:8.0
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
      placement:
        constraints:
          - node.role == manager
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: inventory
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inventory-overlay
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  api:
    image: inventory-api:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=db;Database=inventory;User=root;Password=secret;
    networks:
      - inventory-overlay

  frontend:
    image: inventory-frontend:v2
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 2
        delay: 10s
    environment:
      - API_URL=http://api:8081
    networks:
      - inventory-overlay
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress

volumes:
  db_data:

networks:
  inventory-overlay:
    driver: overlay
    attachable: true